version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - frontend

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
    labels:
      - dependencies
      - github_actions
